### PR TITLE
Logging to MongoDB

### PR DESCRIPTION
**Pull request by donovanlopez**
I added all the logging related stuff in the /logging folder. I also added a writeToMongo() function call to start.js. I added mongo.js to connect to mongoDB but it might be redundant because it's connected somewhere else I think. But I put it there just in case.

### CODE REVIEW

**Review by trevhud — COMMENTED** [review]
Code looks good. @edo92 can you review and approve if it's ready to go?

**Comment by edo92** [comment]
i already have mongodb set up. what does this do ? what messages ?

**Comment by trevhud** [comment]
> i already have mongodb set up. what does this do ? what messages ?

These are the automated messages for customers. To tell them to seed or check the system

**Comment by trevhud** [comment]
@edo92 please Approve if ready

**Comment by edo92** [comment]
why do we want to have messaging in raspbarry pi?

**Comment by donovanlopez** [comment]
@edo92 it's for sending log messages to mongodb for clients

**Pull request closed without merging**
